/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Plate: typeof import('./components/plate/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UniCard: typeof import('./components/uni-ui/uni-card/uni-card.vue')['default']
    UniSection: typeof import('./components/uni-ui/uni-section/uni-section.vue')['default']
    UniSwiperDot: typeof import('./components/uni-ui/uni-swiper-dot/uni-swiper-dot.vue')['default']
  }
}
